# Generated by Django 3.0 on 2020-03-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_proses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('tgl_uplod', models.DateField()),
                ('file_naskah', models.FileField(upload_to='Naskah/file/')),
            ],
        ),
    ]
